/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_flyjingfish_androidaop_NativeUtils */

#ifndef _Included_com_flyjingfish_androidaop_NativeUtils
#define _Included_com_flyjingfish_androidaop_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_flyjingfish_androidaop_NativeUtils
 * Method:    hello_jni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_flyjingfish_androidaop_NativeUtils_hello_1jni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
