site_name: AndroidAOP
site_description: Help you transform into an Android platform framework with AOP architecture
site_author: FlyJingFish
site_url:   https://flyjingfish.github.io/AndroidAOP/
remote_branch: gh-pages
edit_uri: ""

# Repository
repo_name: FlyJingFish/AndroidAOP
repo_url: https://github.com/FlyJingFish/AndroidAOP

# Copyright
copyright: 'Copyright &copy; 2024 FlyJingFish'

# Configuration
theme:
  name: material
  language: en
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/web_logo.svg
  logo: assets/web_logo.svg
  logo_dark: assets/web_logo.svg
#  icon:
#    logo: logo

# Plugins
plugins:
  - blog
  - search:
#      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true


# Additional configuration
extra:
#  generator: false
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FlyJingFish
  alternate:
    - name: English
      link: ''
      lang: en
    - name: 中文
      link: zh/
      lang: zh

# CSS
extra_css:
  - 'css/site.css'

extra_javascript:
  - js/language-switch.js
  - js/header-button.js

# Extensions
markdown_extensions:
  - codehilite
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
#      repo_url_shorthand: true #@其他仓库
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg


nav:
  - 'English':
      - 'Overview': index.md
      - 'Getting Started': getting_started.md
      - 'Extension Library': android_aop_extra.md
      - '@AndroidAopPointCut': AndroidAopPointCut.md
      - '@AndroidAopMatchClassMethod': AndroidAopMatchClassMethod.md
      - '@AndroidAopReplaceClass': AndroidAopReplaceClass.md
      - '@AndroidAopModifyExtendsClass': AndroidAopModifyExtendsClass.md
      - '@AndroidAopCollectMethod': AndroidAopCollectMethod.md
      - 'AOP-Code Helper': AOP_Helper.md
      - 'ProceedJoinPoint': ProceedJoinPoint.md
      - 'ProceedReturn': ProceedReturn.md
      - 'Pointcut method return value': Pointcut_return.md
      - 'Suspend pointcut function': Suspend_cut.md
      - 'About obfuscation': About_obfuscation.md
      - 'Implications': Implications.md
      - 'AspectJ Migration Guide': AspectJ_Migration_Guide.md
      - 'FAQ': FAQ.md
      - 'Tips': give_list.md
  - '中文':
      - '概述': zh/index.md
      - '入门': zh/getting_started.md
      - '扩展库': zh/android_aop_extra.md
      - '@AndroidAopPointCut': zh/AndroidAopPointCut.md
      - '@AndroidAopMatchClassMethod': zh/AndroidAopMatchClassMethod.md
      - '@AndroidAopReplaceClass': zh/AndroidAopReplaceClass.md
      - '@AndroidAopModifyExtendsClass': zh/AndroidAopModifyExtendsClass.md
      - '@AndroidAopCollectMethod': zh/AndroidAopCollectMethod.md
      - 'AOP 代码生成助手': zh/AOP_Helper.md
      - 'ProceedJoinPoint': zh/ProceedJoinPoint.md
      - 'ProceedReturn': zh/ProceedReturn.md
      - '切点方法返回值': zh/Pointcut_return.md
      - 'Suspend 切点函数': zh/Suspend_cut.md
      - '关于混淆': zh/About_obfuscation.md
      - '切面启示': zh/Implications.md
      - 'AspectJ 迁移指南': zh/AspectJ_Migration_Guide.md
      - '常见问题': zh/FAQ.md
      - '打赏本库': zh/give_list.md

validation:
  links:
    absolute_links: ignore
  nav:
    omitted_files: ignore