plugins {
    id 'com.android.library'
    id 'com.google.devtools.ksp'
}
apply from: "$rootDir/gradle/android_base.gradle"
apply from: "$rootDir/gradle/android_publish.gradle"
android {
    namespace 'com.flyjingfish.android_aop_extra'
}

dependencies {
    compileOnly libs.androidx.lifecycle.common.jvm
    implementation project(path: ':android-aop-annotation')
    implementation project(path: ':android-aop-core')
    ksp project(':android-aop-apt')
}